name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Deploy to Netlify
        run: |
          netlify deploy --prod \
            --dir ./static \
            --functions ./netlify/functions \
            --site 2e5c958b-ce1a-4bc6-a933-6ed6fdbb9928 \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --message "Deploy from GitHub Actions"
